version: '3.8'

services:
    app:
        build: .
        volumes:
            - .:/app
        ports:
            - '8000:8000'
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: transfer-pay
            DB_USERNAME: root
            DB_PASSWORD: password
        depends_on:
            - db
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'transfer-pay'
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_PASSWORD: 'password'
        ports:
            - '3306:3306'
